Traceback (most recent call last):
  File "/local/295391/main.py", line 136, in <module>
    posterior_samples = metropolis_hasting(rng_key, max_samples, assumption_variance, Xu_noise, jnp.eye(2)*prior_var, param_iter, Xu_fixed, Xf, Y)
  File "/local/295391/include/mcmc_posterior.py", line 47, in metropolis_hasting
    x_new = random.multivariate_normal(key_new, xvague_sample_current, jnp.eye(num_vague) * assumption_variance)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/random.py", line 792, in multivariate_normal
    return _multivariate_normal(key, mean, cov, shape, dtype, method)  # type: ignore
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 179, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 248, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr, attrs_tracked = _python_pjit_helper(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 136, in _python_pjit_helper
    infer_params_fn(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/api.py", line 325, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 495, in common_infer_params
    jaxpr, consts, out_shardings, out_layouts_flat, attrs_tracked = _pjit_jaxpr(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 1150, in _pjit_jaxpr
    jaxpr, final_consts, out_type, attrs_tracked = _create_pjit_jaxpr(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/linear_util.py", line 350, in memoized_fun
    ans = call(fun, *args)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 1089, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts, attrs_tracked = pe.trace_to_jaxpr_dynamic(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/profiler.py", line 336, in wrapper
    return func(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2314, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, attrs_tracked = trace_to_subjaxpr_dynamic(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2336, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/linear_util.py", line 192, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/random.py", line 806, in _multivariate_normal
    raise ValueError(msg.format(n=n, shape=np.shape(cov)))
ValueError: multivariate_normal requires cov.shape == (..., n, n) for n=4, but got cov.shape == (2, 2).
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[16680,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0624'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
