ERROR: Exception:
Traceback (most recent call last):
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/pip/_internal/commands/uninstall.py", line 105, in run
    uninstall_pathset = req.uninstall(
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 687, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 375, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 415, in _allowed_to_proceed
    return ask("Proceed (Y/n)? ", ("y", "n", "")) != "n"
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 194, in ask
    response = input(message)
EOFError: EOF when reading a line


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 23.7.3

Please update conda by running

    $ conda update -n base -c defaults conda


WARNING: jax 0.4.14 does not provide the extra 'cuda11_cudnn82'
Traceback (most recent call last):
  File "/local/232506/main.py", line 2, in <module>
    import jax
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 73, in <module>
    version = check_jaxlib_version(
  File "/home/yanw/.conda/envs/noise/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 62, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.4.7, but this version of jax requires version >= 0.4.11.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[24133,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: cannot stat '*.pdf': No such file or directory
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0830'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
