Traceback (most recent call last):
  File "/local/293507/main.py", line 133, in <module>
    mcmc = run_mcmc(Xu_fixed, Xf, Y, Xu_noise, jnp.array([jnp.eye(Xu_noise[1].shape) for _ in range(number_u)]) * prior_var, param_iter, num_samples=num_samples,
  File "/local/293507/main.py", line 133, in <listcomp>
    mcmc = run_mcmc(Xu_fixed, Xf, Y, Xu_noise, jnp.array([jnp.eye(Xu_noise[1].shape) for _ in range(number_u)]) * prior_var, param_iter, num_samples=num_samples,
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 2476, in eye
    N_int = core.canonicalize_dim(N, "'N' argument of jnp.eye()")
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/core.py", line 2128, in canonicalize_dim
    return canonicalize_shape((d,), context)[0]
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/core.py", line 2117, in canonicalize_shape
    raise _invalid_shape_error(shape, context)
TypeError: Shapes must be 1D sequences of concrete values of integer type, got ((2,),). 'N' argument of jnp.eye().
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14742,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0615'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
mv: cannot stat '*.log': No such file or directory
