/local/293700/main.py:183: RuntimeWarning: invalid value encountered in sqrt
  plt.fill_between(Xu_fixed[:,0].flatten(), y_pred - 1.96 * np.sqrt(np.diag(_)), y_pred + 1.96 * np.sqrt(np.diag(_)),
Traceback (most recent call last):
  File "/local/293700/main.py", line 183, in <module>
    plt.fill_between(Xu_fixed[:,0].flatten(), y_pred - 1.96 * np.sqrt(np.diag(_)), y_pred + 1.96 * np.sqrt(np.diag(_)),
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2598, in fill_between
    return gca().fill_between(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5431, in fill_between
    return self._fill_between_x_or_y(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5343, in _fill_between_x_or_y
    raise ValueError(f"{name!r} is not 1-dimensional")
ValueError: 'y1' is not 1-dimensional
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1294,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0617'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
