Traceback (most recent call last):
  File "/local/294788/main.py", line 117, in <module>
    mcmc = run_mcmc(Xu_fixed, Xf, Y, Xu_noise, prior_var*jnp.eye(2), param_iter, num_samples=num_mcmc,
  File "/local/294788/include/mcmc_posterior.py", line 124, in run_mcmc
    mcmc.run(rng_key, Xfz, Xfg, Y_data, prior_mean, prior_cov, init_params)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 666, in run
    states_flat, last_state = partial_map_fn(map_args)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 438, in _single_chain_mcmc
    new_init_state = self.sampler.init(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 749, in init
    init_params = self._init_state(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 693, in _init_state
    ) = initialize_model(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/util.py", line 656, in initialize_model
    ) = _get_model_transforms(substituted_model, model_args, model_kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/util.py", line 450, in _get_model_transforms
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/local/294788/include/mcmc_posterior.py", line 112, in model
    z_flat = numpyro.sample('z_uncertain_flat', dist.LogNormal(prior_mean_flat, covariance_matrix=prior_cov_flat))
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/distributions/distribution.py", line 99, in __call__
    return super().__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'covariance_matrix'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[45472,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0621'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
mv: cannot stat '*.log': No such file or directory
