	Adding nVidia Cuda Toolkit 11.8
	Adding nVidia cuDNN 8.6 (.0.163)
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Sampling: [z_uncertain0, z_uncertain1, z_uncertain10, z_uncertain11, z_uncertain12, z_uncertain13, z_uncertain14, z_uncertain15, z_uncertain16, z_uncertain17, z_uncertain18, z_uncertain19, z_uncertain2, z_uncertain3, z_uncertain4, z_uncertain5, z_uncertain6, z_uncertain7, z_uncertain8, z_uncertain9]
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    trace = posterior_inference_mcmc(Xu_noise, jnp.eye(2)*prior_var, param_iter, Xu_fixed, Xf, Y)  #TODO: Y
  File "/local/236200/include/mcmc_posterior.py", line 37, in posterior_inference_mcmc
    z_uncertain_samples = [trace_prior['z_uncertain' + str(i)][0] for i in range(prior_mean.shape[0])]
  File "/local/236200/include/mcmc_posterior.py", line 37, in <listcomp>
    z_uncertain_samples = [trace_prior['z_uncertain' + str(i)][0] for i in range(prior_mean.shape[0])]
  File "/home/yanw/.local/lib/python3.8/site-packages/arviz/data/inference_data.py", line 258, in __getitem__
    raise KeyError(key)
KeyError: 'z_uncertain0'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35162,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0920'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
