	Adding nVidia Cuda Toolkit 11.8
	Adding nVidia cuDNN 8.6 (.0.163)
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 2015, in array
    dtype = dtypes._lattice_result_type(*leaves)[0] if leaves else dtypes.float_
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 537, in _lattice_result_type
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 537, in <genexpr>
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 360, in _dtype_and_weaktype
    return dtype(value), any(value is typ for typ in _weak_types) or is_weakly_typed(value)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 532, in dtype
    raise TypeError(f"Value '{x}' with dtype {dt} is not a valid JAX array "
TypeError: Value '[z_uncertain0 z_uncertain1 z_uncertain2 z_uncertain3 z_uncertain4
 z_uncertain5 z_uncertain6 z_uncertain7 z_uncertain8 z_uncertain9
 z_uncertain10 z_uncertain11 z_uncertain12 z_uncertain13 z_uncertain14
 z_uncertain15 z_uncertain16 z_uncertain17 z_uncertain18 z_uncertain19]' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 81, in <module>
    trace = posterior_inference_mcmc(Xu_noise, jnp.eye(2)*prior_var, param_iter, Xu_fixed, Xf, Y)  #TODO: Y
  File "/local/236224/include/mcmc_posterior_1.py", line 38, in posterior_inference_mcmc
    z_uncertain = jnp.array(z_uncertain_samples)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 2020, in array
    dtype = dtypes._lattice_result_type(*leaves)[0]
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 537, in _lattice_result_type
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 537, in <genexpr>
    dtypes, weak_types = zip(*(_dtype_and_weaktype(arg) for arg in args))
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 360, in _dtype_and_weaktype
    return dtype(value), any(value is typ for typ in _weak_types) or is_weakly_typed(value)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 532, in dtype
    raise TypeError(f"Value '{x}' with dtype {dt} is not a valid JAX array "
TypeError: Value '[z_uncertain0 z_uncertain1 z_uncertain2 z_uncertain3 z_uncertain4
 z_uncertain5 z_uncertain6 z_uncertain7 z_uncertain8 z_uncertain9
 z_uncertain10 z_uncertain11 z_uncertain12 z_uncertain13 z_uncertain14
 z_uncertain15 z_uncertain16 z_uncertain17 z_uncertain18 z_uncertain19]' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[4056,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0920'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
